export const discs = [
  {
    _id: 1,
    title: `Flat 2nd Run Discmania CD2`,
    brand: 'Discmania',
    type: 'fairway',
    mold: 'CD2',
    basePlastic: 'S-Line',
    subPlastic: 'Swirly',
    run: '2nd Run',
    condition: 7,
    price: 30,
    image: '/media/discs/disc2.jpeg',
  },
  {
    _id: 2,
    title: `Discmania Fd3 2nd run Lizotte FAF`,
    brand: 'Discmania',
    type: 'fairway',
    mold: 'FD3',
    basePlastic: 'S-Line',
    subPlastic: 'Swirly',
    run: '2nd Run Lizotte',
    condition: 10,
    price: 125,
    image: '/media/discs/disc3.jpeg',
  },
  {
    _id: 3,
    title: `1st Run PD2 Discmania`,
    brand: 'Discmania',
    type: 'distance',
    mold: 'PD2',
    basePlastic: 'C-Line',
    run: '1st Run',
    condition: 8,
    price: 50,
    image: '/media/discs/disc4.jpeg',
  },
  {
    _id: 4,
    title: `Discmania D-Line P2 Chef Special Swords Stamp`,
    brand: 'Discmania',
    type: 'putter',
    mold: 'P2',
    basePlastic: 'D-Line',
    run: 'Stock',
    condition: 5,
    price: 15,
    image: '/media/discs/disc5.jpeg',
  },
  {
    _id: 5,
    title: `Discmania Color Glow DD3 RARE`,
    brand: 'Discmania',
    type: 'distance',
    mold: 'DD3',
    basePlastic: 'C-Line',
    subPlastic: 'Glow',
    run: 'Mystery Box CG',
    condition: 9,
    price: 60,
    image: '/media/discs/disc6.jpeg',
  },
  {
    _id: 6,
    title: `Iron Samurai II MD3 Eagle McMahon`,
    brand: 'Discmania',
    type: 'mid',
    mold: 'MD3',
    basePlastic: 'C-Line',
    subPlastic: 'Metal-Flake Glow',
    run: 'Iron Samurai 2',
    condition: 10,
    price: 80,
    image: '/media/discs/disc8.jpeg',
  },
  {
    _id: 7,
    title: `Rick Wysocki Destroyer`,
    brand: 'Innova',
    type: 'distance',
    mold: 'Destroyer',
    basePlastic: 'Star',
    run: 'Ricky Wysocki 2X',
    condition: 7,
    price: 22,
    image: '/media/discs/disc9.jpeg',
  },
  {
    _id: 8,
    title: `Rare Tilt -- OVERSTABLE`,
    brand: 'Discmania',
    type: 'fairway',
    mold: 'Tilt',
    basePlastic: 'Exo Hard',
    subPlastic: 'Vapor',
    run: '1st Run',
    condition: 9,
    price: 75,
    image: '/media/discs/disc10.jpeg',
  },
  {
    _id: 9,
    title: `Sky God 1`,
    brand: 'Discmania',
    type: 'putter',
    mold: 'P2',
    basePlastic: 'C-Line',
    run: 'Sky God 1',
    condition: 7,
    price: 100,
    image: '/media/discs/disc12.jpeg',
  },
  {
    _id: 10,
    title: `Eagle Broken Claw Tactic`,
    brand: 'Discmania',
    type: 'approach',
    mold: 'Tactic',
    basePlastic: 'Lux',
    subPlastic: 'Vapor',
    run: 'Broken Claw',
    condition: 8,
    price: 55,
    image: '/media/discs/disc14.jpeg',
  },
  {
    _id: 11,
    title: `Mini Shield Stamp C-Line P2`,
    brand: 'Discmania',
    type: 'putter',
    mold: 'P2',
    basePlastic: 'C-Line',
    condition: 10,
    price: 15,
    image: '/media/discs/disc15.jpeg',
  },
  {
    _id: 12,
    title: `Discmania Enigma`,
    brand: 'Discmania',
    type: 'distance',
    mold: 'Enigma',
    basePlastic: 'Neo',
    run: 'Stock',
    condition: 9,
    price: 12,
    image: '/media/discs/disc16.jpeg',
  },
  {
    _id: 13,
    title: `Neo Tactic Marbly Plastic`,
    brand: 'Discmania',
    type: 'approach',
    mold: 'Tactic',
    basePlastic: 'Neo',
    run: 'Stock',
    condition: 10,
    price: 25,
    image: '/media/discs/disc17.jpeg',
  },
  {
    _id: 14,
    title: `Vapor Method w/Halo`,
    brand: 'Discmania',
    type: 'mid',
    mold: 'Method',
    basePlastic: 'Lux',
    subPlastic: 'Vapor',
    run: 'Stock',
    condition: 9,
    price: 18,
    image: '/media/discs/disc18.jpeg',
  },
  {
    _id: 15,
    title: `Discmania 10th Anniversary Logic`,
    brand: 'Discmania',
    type: 'putter',
    mold: 'Logic',
    basePlastic: 'C-Line',
    run: '10th Anniversary',
    condition: 10,
    price: 35,
    image: '/media/discs/disc19.jpeg',
  },
  {
    _id: 16,
    title: `Brand New Cloudbreaker3!`,
    brand: 'Discmania',
    type: 'distance',
    mold: 'DD3',
    basePlastic: 'S-Line',
    run: 'Cloudbreaker 3',
    condition: 10,
    price: 75,
    image: '/media/discs/disc20.jpeg',
  },
];
